/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package productos;


import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanalvarenga
 */
public class CajaFacturacion extends javax.swing.JFrame {

    DefaultTableModel modelo; // declaración a nivel de clase

    /**
     * Creates new form CajaFacturacion
     */
    
    private DefaultTableModel modelBox;
    
    public CajaFacturacion() {
        initComponents();
        modelBox = (DefaultTableModel) tablaProductos.getModel();
    }
    
    public void agregarDatoATabla(String dato) {
        
        modelBox.addRow(new Object[]{"", dato});
    }

    private void calcularTotales() {

        double totalFila = 0.0;
        int totalFilas = modelo.getRowCount();

        for (int i = 0; i < totalFilas; i++) {
            var valorColumnaTotal = modelo.getValueAt(i, 3).toString();
            totalFila += Double.parseDouble(valorColumnaTotal);
        }

        DecimalFormat formatISV = new DecimalFormat("0.##");

        double isv = totalFila * 0.15;
        String isvFormateado = formatISV.format(isv);

        double tp = totalFila + isv;

        txtSubTotal.setText("" + totalFila);
        txtISV.setText(isvFormateado);
        txtTotal.setText("" + tp);

    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtISV = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de venta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Sub-Total:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("I.S.V:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Total a Pagar:");

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtISV.setEditable(false);
        txtISV.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtISV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtISV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtISV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // Forma de inicialización 1
        //String[] columnas = {"Cantidad", "Nombre producto", "Precio", "Total"};
        //modelo = new DefaultTableModel(null, columnas);
        //Forma de inicialización 2
        //Instanciando el modelo
        
        /*DefaultComboBoxModel model = new DefaultComboBoxModel();
        String combo;

        model.addElement(null);
        model.addElement("Sandia");
        model.addElement("Carne molida");
        model.addElement("Tajadas de platani fito");
        model.addElement("Leche");
        model.addElement("Bananas");
        model.addElement("Papel Toalla");

        combo.setModel(model);
        
        String valor = String.valueOf(combo.getSelectedItem());
        int index = combo.getSelectedIndex();*/
        
        modelo = new DefaultTableModel() {

            //deshabilitar la edición de las filas
            public boolean isCellEditable(int row, int col) {
                return false;
            }

        };

        //Defino las Columnas
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Total");

        //agrego el modelo a la tabla
        tablaProductos.setModel(modelo);

        //cambiar tamaño a las columnas
        //la columna de la cantidad
        tablaProductos.getColumnModel().getColumn(0).setMaxWidth(100);
        tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(100);

        //la columna de la productos
        tablaProductos.getColumnModel().getColumn(1).setMaxWidth(400);
        tablaProductos.getColumnModel().getColumn(1).setPreferredWidth(400);


    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Instanciar el cuadro ed dialogo y mostrarlo en pantalla
        String dato;
        ProductoDialog ventana = new ProductoDialog(this, true);
        ventana.setVisible(true);

        //Obtener los valores del dialogo
        if (ventana.getRootPane() == null) {
            return;
        }
        
        int cantidad = ventana.getCantidad();
        String valorSeleccionado = ventana.getComboBoxValue();
        double precio = ventana.getPrecio();        
        double total = cantidad * precio;

        //agregar la fila
        Vector fila = new Vector();

        fila.addElement(cantidad);
        fila.addElement(valorSeleccionado);                         
        fila.addElement(precio);
        fila.addElement(total);
        
        
        
        modelo.addRow(fila);
        calcularTotales();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // Obtener el índice de la fila seleccionada en la tabla
        int selecProduc = tablaProductos.getSelectedRow();

        if (selecProduc != -1) { // -1 significa que no se ha seleccionado ninguna fila
            // Eliminar la fila seleccionada de la tabla
            modelo = (DefaultTableModel) tablaProductos.getModel();
            modelo.removeRow(selecProduc);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        calcularTotales();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        // Obtener la fila seleccionada
        int selecProduc = tablaProductos.getSelectedRow();
        
        // Verificar si se ha seleccionado una fila
        if (selecProduc == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para modificar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Obtener datos actuales de la fila seleccionada
        int cantidad = (int) modelo.getValueAt(selecProduc, 0);
        String producto = (String) modelo.getValueAt(selecProduc, 1);
        double precio = (double) modelo.getValueAt(selecProduc, 2);
        
            
        ProductoDialog ventana = new ProductoDialog(this, true);
        ventana.setVisible(true);

        //Obtener los valores del dialogo
        if (ventana.getRootPane() == null) {
            return;
        }

        
        int nuevaCant = ventana.getCantidad();
        String nuevoValorSeleccionado = ventana.getComboBoxValue();
        double nuevoPrecio = ventana.getPrecio();        
        double nuevoTotal = nuevaCant * nuevoPrecio;
                   
             
        // Actualizar datos en la tabla si se proporcionan nuevos valores
            if (Integer.toString(nuevaCant) != null && nuevoValorSeleccionado != null && Double.toString(nuevoPrecio) != null) {
                modelo.setValueAt(nuevaCant, selecProduc, 0);
                modelo.setValueAt(nuevoValorSeleccionado, selecProduc, 1);
                modelo.setValueAt(nuevoPrecio, selecProduc, 2);
                modelo.setValueAt(nuevoTotal, selecProduc, 3);
            }
        calcularTotales();
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CajaFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtISV;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
